import { Injectable, NotFoundException } from '@nestjs/common';
import { Template } from '../../../common/interfaces';

@Injectable()
export class TemplatesService {
  private readonly templates: Template[] = [
    {
      id: 'story-based',
      name: 'Story-Based Post',
      category: 'engagement',
      structure: [
        '[Hook — a surprising or emotional opening line]',
        '',
        '[Set the scene — 1-2 sentences of context]',
        '',
        '[The conflict or challenge — what went wrong or was difficult]',
        '',
        '[The turning point — what changed]',
        '',
        '[The lesson — what you learned]',
        '',
        '[Call to action — ask a question or invite reflection]',
      ].join('\n'),
      example: [
        'I almost quit my engineering career 3 years ago.',
        '',
        'I was burnt out, working 70-hour weeks, and felt invisible despite shipping features nonstop.',
        '',
        'Then my manager said something that changed everything:',
        '"You\'re building the wrong things really fast."',
        '',
        'That one sentence shifted my focus from output to impact.',
        'I started asking "why" before "how" — and everything changed.',
        '',
        'What was the best career advice you ever received?',
      ].join('\n'),
      tips: [
        'Open with a hook that creates curiosity or emotional tension',
        'Keep paragraphs to 1-2 lines for mobile readability',
        'The lesson should feel earned, not preachy',
        'End with a question that invites personal stories',
      ],
    },
    {
      id: 'lesson-learned',
      name: 'Lesson Learned',
      category: 'thought-leadership',
      structure: [
        '[Bold statement or counterintuitive take]',
        '',
        '[Context — briefly describe the situation]',
        '',
        '[What you tried first — and why it didn\'t work]',
        '',
        '[What actually worked — the key insight]',
        '',
        '[Numbered takeaways — 3-5 actionable points]',
        '',
        '[Closing thought + question]',
      ].join('\n'),
      example: [
        'The best code review I ever received had zero comments about code.',
        '',
        'A senior engineer looked at my PR and asked: "What problem does this solve for users?"',
        '',
        'I had spent 3 days over-engineering a solution for a problem no one had.',
        '',
        'Lessons that stuck:',
        '1. Start with the user problem, not the technical solution',
        '2. The best code is the code you don\'t write',
        '3. Over-engineering is a form of procrastination',
        '',
        'What\'s the most valuable feedback you\'ve received on your work?',
      ].join('\n'),
      tips: [
        'The opening statement should challenge conventional wisdom',
        'Be specific — vague lessons don\'t resonate',
        'Numbered lists get 40% more engagement on LinkedIn',
        'Vulnerability builds trust; don\'t be afraid to share mistakes',
      ],
    },
    {
      id: 'hot-take',
      name: 'Hot Take / Opinion',
      category: 'engagement',
      structure: [
        '[Controversial or strong opinion — stated clearly]',
        '',
        '[Why most people disagree or do the opposite]',
        '',
        '[Your evidence or reasoning — 2-3 supporting points]',
        '',
        '[Acknowledge the nuance — when the opposite is true]',
        '',
        '[Restate your position with a call to engage]',
      ].join('\n'),
      example: [
        'Unpopular opinion: Leetcode-style interviews are broken.',
        '',
        'Most companies use them because they\'re "standard" — not because they predict job performance.',
        '',
        'Here\'s what I\'ve seen after hiring 50+ engineers:',
        '→ The best performers excelled at system design, not algorithms',
        '→ Communication skills predicted success more than coding speed',
        '→ Take-home projects revealed 10x more signal than whiteboards',
        '',
        'Are there roles where algorithm skills matter? Absolutely.',
        'But for most product engineering roles? We can do better.',
        '',
        'Agree or disagree? I\'d love to hear how your company hires.',
      ].join('\n'),
      tips: [
        'Strong opinions get engagement — but back them with evidence',
        'Use "→" arrows for visual contrast in list points',
        'Always acknowledge nuance to avoid seeming absolutist',
        'Invite debate in the CTA — disagreement drives comments',
      ],
    },
    {
      id: 'behind-the-scenes',
      name: 'Behind the Scenes',
      category: 'authenticity',
      structure: [
        '[Attention-grabbing reveal about your process or work]',
        '',
        '[What people see from the outside]',
        '',
        '[What actually happens behind the scenes — be specific]',
        '',
        '[The messy reality — failures, iterations, long nights]',
        '',
        '[What you\'d want people to know]',
        '',
        '[Relatable closing + question]',
      ].join('\n'),
      example: [
        'That "overnight" product launch took us 9 months.',
        '',
        'What you saw: a polished launch post with 500 likes.',
        '',
        'What actually happened:',
        '- 3 failed prototypes before we found product-market fit',
        '- A complete technical pivot at month 4',
        '- Launch day had 2 critical bugs we fixed at 2 AM',
        '- The "growth hack" was 200 personal DMs over 3 weeks',
        '',
        'There\'s no shortcut to building something people want.',
        'Just iteration, feedback, and stubborn optimism.',
        '',
        'What\'s something in your career that looked easy from the outside?',
      ].join('\n'),
      tips: [
        'Contrast the polished outcome with the messy process',
        'Use bullet points with dashes for the "reality" section',
        'Specificity is credibility — include real numbers and timelines',
        'This format builds trust and humanizes your personal brand',
      ],
    },
    {
      id: 'achievement-milestone',
      name: 'Achievement / Milestone',
      category: 'celebration',
      structure: [
        '[The milestone — stated clearly with emotion]',
        '',
        '[Why it matters to you personally]',
        '',
        '[The journey — key moments that got you here]',
        '',
        '[People you want to thank — be specific]',
        '',
        '[What\'s next — forward-looking statement]',
        '',
        '[Invite others to share their wins]',
      ].join('\n'),
      example: [
        'Just passed 10,000 followers on LinkedIn. 🎉',
        '',
        '12 months ago I had 400 connections and had never written a post.',
        '',
        'What changed:',
        '→ Started posting consistently (3x/week, no exceptions)',
        '→ Focused on sharing real lessons, not motivational fluff',
        '→ Engaged with 20 posts every morning before writing my own',
        '→ Every post that "flopped" taught me something valuable',
        '',
        'Biggest thanks to this community. Your comments and DMs kept me going.',
        '',
        'Next goal: Turn this into a weekly newsletter about engineering leadership.',
        '',
        'What milestone are you working toward right now?',
      ].join('\n'),
      tips: [
        'Lead with the number or achievement for instant hook value',
        'Share the "before" to make the "after" more impressive',
        'Be generous with credit — tag people when appropriate',
        'A forward-looking statement keeps momentum and curiosity',
      ],
    },
    {
      id: 'industry-insight',
      name: 'Industry Insight',
      category: 'thought-leadership',
      structure: [
        '[Trend or observation — what you\'re seeing in the industry]',
        '',
        '[Data or evidence — support your observation]',
        '',
        '[What it means — implications for your audience]',
        '',
        '[Your prediction — where this is heading]',
        '',
        '[Actionable advice — what your audience should do now]',
        '',
        '[Invite discussion]',
      ].join('\n'),
      example: [
        'AI isn\'t replacing developers. It\'s creating two tiers of them.',
        '',
        'I\'ve noticed a clear pattern across 20+ engineering teams:',
        '→ Developers using AI tools ship 2-3x faster',
        '→ But the quality gap is growing, not shrinking',
        '→ AI-assisted code without strong fundamentals = technical debt at scale',
        '',
        'My prediction: Within 2 years, "AI-native developer" will be a job requirement,',
        'not a nice-to-have. The bar for entry isn\'t lower — it\'s different.',
        '',
        'What to do now:',
        '1. Master prompt engineering for code generation',
        '2. Double down on system design and architecture skills',
        '3. Learn to review AI-generated code critically',
        '',
        'How is AI changing the way your team builds software?',
      ].join('\n'),
      tips: [
        'Lead with an observation that challenges the dominant narrative',
        'Use specific numbers and examples to build credibility',
        'Predictions drive engagement — people love to agree or disagree',
        'Actionable advice makes your post save-worthy',
      ],
    },
    {
      id: 'career-advice',
      name: 'Career Advice',
      category: 'mentorship',
      structure: [
        '[Advice framed as something you wish you knew earlier]',
        '',
        '[The mistake you made or saw others make]',
        '',
        '[Why the conventional approach fails]',
        '',
        '[Your better approach — 3-5 specific tactics]',
        '',
        '[Results you\'ve seen from this approach]',
        '',
        '[Encouragement + question]',
      ].join('\n'),
      example: [
        'If I could go back 5 years, I\'d tell myself: "Stop optimizing your resume. Start building your network."',
        '',
        'I spent months tweaking bullet points when I should have been having coffee chats.',
        '',
        'The uncomfortable truth: 70% of jobs are filled through referrals.',
        'Your perfect resume lands in the same pile as 500 others.',
        '',
        'What actually moves the needle:',
        '1. Reach out to 5 people in your target role per week',
        '2. Ask for insight, not for a job',
        '3. Share what you\'re learning publicly on LinkedIn',
        '4. Follow up with value, not asks',
        '',
        'Every career opportunity I\'ve had in the last 3 years came from relationships, not applications.',
        '',
        'What\'s one piece of career advice that changed your trajectory?',
      ].join('\n'),
      tips: [
        'Personal regret + specific advice = high engagement formula',
        'Statistics add weight to career advice posts',
        'Make advice actionable with numbered steps people can start today',
        'End with a question that prompts personal stories',
      ],
    },
    {
      id: 'question-engagement',
      name: 'Question / Engagement',
      category: 'engagement',
      structure: [
        '[Context — brief setup for the question (1-2 lines)]',
        '',
        '[The question — clear, specific, and easy to answer]',
        '',
        '[Your answer — share your perspective first]',
        '',
        '[Optional: A few more related questions to spark discussion]',
      ].join('\n'),
      example: [
        'I\'ve been thinking about this a lot lately:',
        '',
        'What\'s the one skill that has had the biggest impact on your career — that you didn\'t learn in school?',
        '',
        'For me, it\'s writing. Clear writing = clear thinking.',
        'It\'s helped me ship better specs, win buy-in from stakeholders,',
        'and now it\'s building my personal brand on LinkedIn.',
        '',
        'Runner up: Knowing when to say no.',
        '',
        'What\'s yours? Drop it below 👇',
      ].join('\n'),
      tips: [
        'Questions that can be answered in one sentence get the most replies',
        'Always share your own answer first to model the type of response',
        'Avoid yes/no questions — open-ended drives better engagement',
        'Posts with high comment counts get algorithmic amplification',
      ],
    },
  ];

  getTemplates(category?: string): Template[] {
    if (category) {
      return this.templates.filter(
        (t) => t.category.toLowerCase() === category.toLowerCase(),
      );
    }
    return this.templates;
  }

  getTemplateById(id: string): Template {
    const template = this.templates.find((t) => t.id === id);
    if (!template) {
      throw new NotFoundException(`Template with ID "${id}" not found`);
    }
    return template;
  }

  getCategories(): string[] {
    const categories = new Set(this.templates.map((t) => t.category));
    return [...categories];
  }
}
