apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: forgewind
  labels:
    app: api-gateway
    app.kubernetes.io/part-of: forgewind
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
